#!/usr/bin/python
try:
	import lxml.etree as ET
except ImportError, ex:
	ex.args = '%s; please install the python-lxml package <http://codespeak.net/lxml/>' % str(ex),
	raise
import sys
import re
from djvu import miniexp

hocr_class_to_djvu = \
dict(
	ocr_page = 'page',
	ocr_column = 'column',
	ocr_par = 'para',
	ocr_line = 'line',
	ocrx_block = 'region',
	ocrx_line = 'line',
	ocrx_word = 'word'
).get

BBOX_RE = re.compile(
	r'''
		bbox \s+
		(?P<x0> \d+) \s+ 
		(?P<y0> \d+) \s+
		(?P<x1> \d+) \s+
		(?P<y1> \d+)
	''', re.VERBOSE)

class BBox(object):

	def __init__(self, x0 = None, y0 = None, x1 = None, y1 = None):
		self._coordinates = [x0, y0, x1, y1]
	
	@property
	def x0(self):
		return self[0]
	@property

	def y0(self):
		return self[1]

	@property
	def x1(self):
		return self[2]

	@property
	def y1(self):
		return self[3]

	def __getitem__(self, item):
		return self._coordinates[item]

	def __nonzero__(self):
		for value in self._coordinates:
			if value is None:
				return False
		return False

	def update(self, bbox):
		for i, self_i in enumerate(self._coordinates):
			if self_i is None:
				self._coordinates[i] = bbox[i]
			elif i < 2 and bbox[i] is not None and self[i] > bbox[i]:
				self._coordinates[i] = bbox[i]
			elif i > 1 and bbox[i] is not None and self[i] < bbox[i]:
				self._coordinates[i] = bbox[i]

def _scan(node, buffer, parent_bbox):
	def look_down(buffer, parent_bbox):
		have_subresults = False
		for child in node.iterchildren():
			_scan(child, buffer, parent_bbox)
			if node.tail and node.tail.strip():
				buffer.append(node.tail)
		if node.text and node.text.strip():
			buffer.append(node.text)
	if not isinstance(node.tag, basestring):
		return
	hocr_classes = (node.get('class') or '').split()
	djvu_class = None
	for hocr_class in hocr_classes:
		djvu_class = hocr_class_to_djvu(hocr_class)
		if djvu_class:
			break
	if djvu_class:
		m = BBOX_RE.search(node.get('title') or '')
		if m is None:
			bbox = BBox()
		else:
			bbox = BBox(*(int(m.group(id)) for id in ('x0', 'y0', 'x1', 'y1')))
			parent_bbox.update(bbox)
	if djvu_class:
		result = [miniexp.Symbol(djvu_class)]
		result += [None] * 4
		look_down(result, bbox)
		result[1:5] = bbox
		if len(result) == 5:
			result.append('')
		buffer.append(result)
	else:
		look_down(buffer, parent_bbox)

def scan(node):
	buffer = []
	_scan(node, buffer, BBox())
	return buffer

def main():
	doc = ET.parse(sys.stdin, ET.HTMLParser())
	sys.stdout.write('select\nremove-txt\n\n')
	for i, text in enumerate(scan(doc.find('/body'))):
		sys.stdout.write('select %d\nset-txt\n' % (i + 1))
		miniexp.Expression(text).print_into(sys.stdout, 80)
		sys.stdout.write('\n.\n\n')

if __name__ == '__main__':
	main()

# vim:ts=4 sw=4 noet
