#!/bin/sh
[ "$1" = "-l" ] && cat <<EOF
Cuneiform for Linux 1.0.0
Supported languages: eng ger fra rus swe spa ita ruseng ukr srp hrv pol dan por dut cze rum hun bul slo lav lit est tur.
EOF
exit 1

# vim:ts=4 sts=4 sw=4 et
