#!/bin/sh

# Copyright © 2018 Jakub Wilk <jwilk@jwilk.net>
#
# This file is part of ocrodjvu.
#
# ocrodjvu is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# ocrodjvu is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.

set -e -u
cd "${0%/*}/.."
IFS='()' read _ version _ < doc/changelog
python setup.py sdist --formats=tar
target="dist/ocrodjvu-$version.tar"
xz -4ef "$target"

# vim:ts=4 sts=4 sw=4 et
