#!/bin/sh

# Copyright © 2016-2018 Jakub Wilk <jwilk@jwilk.net>
#
# This file is part of ocrodjvu.
#
# ocrodjvu is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# ocrodjvu is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.

PYTHON=${PYTHON:-python}
pyflakes=$(command -v pyflakes) || { echo pyflakes not found >&2; exit 1; }
if [ $# -eq 0 ]
then
    set -- "${0%/*}/.."
fi
# It would be tempting to use "python -m pyflakes" here,
# but that doesn't work in Python 2.6.
! "$PYTHON" "$pyflakes" "$@" \
| grep -v -E "/lib/hocr.py:[0-9]+: list comprehension redefines '[xy][01]' "  # https://bugs.launchpad.net/pyflakes/+bug/1461208

# vim:ts=4 sts=4 sw=4 et
