#!/bin/sh
set -e -u
version=${1:?"no version number provided"}
date="$(date -u --rfc-3339=date)"
PS4='$ '
set -x
dch -m -v "$version" -u low -c doc/changelog
export version date
perl -pi -e 's/^__version__ = \047\K[\w.]+/$ENV{version}/' lib/version.py
perl -pi -e 's/<!ENTITY version \047\K[\w.]+/$ENV{version}/; s/<date>\K[0-9-]+/$ENV{date}/' doc/*.xml
perl -pi -e 's/djvu2hocr \K[\w.]+/$ENV{version}/' tests/djvu2hocr/*.test*
