#!/bin/sh
export version=${1:?"no version number provided"}
set -e
set -x
dch -m -v "$version" -u low -c doc/changelog
perl -pi -e 's/^__version__ = '"'"'\K[\w.]+/$ENV{version}/' lib/version.py
perl -pi -e 's/<(!ENTITY version) '"'"'\K[0-9.]+/$ENV{version}/' doc/*.xml
perl -pi -e 's/djvu2hocr \K[0-9.]+/$ENV{version}/' tests/djvu2hocr/*.test*
