#!/bin/sh
if [ $# -ne 1 ]
then
    printf 'Usage: %s <manpage>\n' "$0" >&2
    exit 1
fi
set -e
# Format URLs consistently:
sed -i~ -e 's,^\(\\%http://.*\),\\m[blue]\\fI\1\\fR\\m[],' "$1"
rm -f "$1~"

# vim:ts=4 sw=4 et
